### ISSUE TITLE
Additional information of requirements needed

### ISSUE THREAD

**Issue by GoldExplosion** [andreped/super-ml-pets#16]
I keep running into this error when trying to install the framework. 

> Namespace(finetune=None, model_name='rl_model', nb_games=10000, nb_retries=1, nb_steps=10000, task='deploy')
> 
> Pausing...
> 
> Running...
> Traceback (most recent call last):
>   File "main.py", line 36, in <module>
>     run(path)
>   File "C:\Users\jivit\Documents\Python_Scripts\RL\super-ml-pets\src\game_interaction\agent.py", line 69, 
> in run
>     model = MaskablePPO.load(model_path)
>   File "C:\Users\jivit\anaconda3\envs\gpu2\lib\site-packages\stable_baselines3\common\base_class.py", line 675, in load
>     path, device=device, custom_objects=custom_objects, print_system_info=print_system_info
>   File "C:\Users\jivit\anaconda3\envs\gpu2\lib\site-packages\stable_baselines3\common\save_util.py", line 
> 419, in load_from_zip_file
>     data = json_to_data(json_data, custom_objects=custom_objects)
>   File "C:\Users\jivit\anaconda3\envs\gpu2\lib\site-packages\stable_baselines3\common\save_util.py", line 
> 164, in json_to_data
>     deserialized_object = cloudpickle.loads(base64_object)
> AttributeError: Can't get attribute '_make_function' on <module 'cloudpickle.cloudpickle' from 'C:\\Users\\jivit\\anaconda3\\envs\\gpu2\\lib\\site-packages\\cloudpickle\\cloudpickle.py'>

I think it is because I am using a different version of stable baselines 3. Can you include the version of sb3_contrib and python you are using?

**Comment by andreped** [comment]
It might be because the the model I trained was using a different python version than the one you are using. I have seen the same when trying to load models through pickle in TensorFlow.

I am working on a separate machine than the one I trained on right now, but I believe they have the same specs. I currently have python 3.7.9 and sb3_contrib 1.6.0.

**Comment by andreped** [comment]
I added the missing requirements and fixed a bug related to windows (currently only supports deployment on windows): e273913b06244f1428c4ecd59a80e1c303db0b06

**Comment by andreped** [comment]
Just tried to reproduce your issue by setting up a virtual environment using Python 3.8.6 instead of 3.7.9, and I got the error prompt below. 3.7.9 works just fine on this machine, even if it a different machine than the one it was trained on, but I believe the python version is the same. So there appear to be a very strict python version requirement when loading pretrained models using sb3.

I will look into it.
```
C:\Users\andrp\workspace\super-ml-pets\venv38\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
C:\Users\andrp\workspace\super-ml-pets\venv38\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
Traceback (most recent call last):
  File ".\main.py", line 43, in <module>
    run(ret.infer_model)
  File "C:\Users\andrp\workspace\super-ml-pets\src\agent.py", line 56, in run
    model = MaskablePPO.load(model_path)
  File "C:\Users\andrp\workspace\super-ml-pets\venv38\lib\site-packages\stable_baselines3\common\base_class.py", line 747, in load
    model._setup_model()
  File "C:\Users\andrp\workspace\super-ml-pets\venv38\lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py", line 167, in _setup_model
    self.clip_range = get_schedule_fn(self.clip_range)
  File "C:\Users\andrp\workspace\super-ml-pets\venv38\lib\site-packages\stable_baselines3\common\utils.py", line 91, in get_schedule_fn
    assert callable(value_schedule)
AssertionError

```

**Comment by andreped** [comment]
Yes, this is what I figured. Python difference causes this: https://github.com/DLR-RM/stable-baselines3/issues/403#issuecomment-825335945

**Comment by andreped** [comment]
What we normally do in TensorFlow, or similar, is to recreate the model and only load the weights. That often solves the problem. However, that is quite annoying and not really scalable when people have trained their own custom models. It would be better if loading in sb3 just worked.

If you have any idea of how to solve this in sb3, let me know.

**Comment by andreped** [comment]
Solved in bba5d0eca07e7c52d50283d4416f9e744ef61c0d.

It was quite simple in the end. Basically what is needed is to provide `custom_objects`. See this thread for an example: https://github.com/DLR-RM/stable-baselines3/issues/589#issuecomment-930561680

**Comment by andreped** [comment]
Also, small mistake in the deployment usage in the README. Fixed now: 3053fa5c3f6803ba369dd685233d3703e59bd95a

Testing usage should be a lot more clearer now (note that it is the `infer_model` arg where we define the pretrained model):
https://github.com/andreped/super-ml-pets#testing-

**Comment by andreped** [comment]
Also fixed transfer learning: 1ee45e68c9d6b96f95df86fc8178206b45b410b9

For any loading of model trained using a different python version, `custom_objects` need to be provided. So I added it both for the training and deployment aspect, with checks.

**Comment by GoldExplosion** [comment]
Yes, It is working now. I was having trouble with my numpy version. I couldn't downgrade it for some reason(it was asking for numpy version 0x10 so I googled and the solution was to downgrade). But after uninstalling and reinstalling latest numpy version(1.23.2), it worked. 
Thanks for your help with this issue ;)

**Comment by andreped** [comment]
@GoldExplosion: Great that it worked out :)

Which python version were you using where you experienced this issue? I could add this to the troubleshoot section of the README.

**Comment by GoldExplosion** [comment]
I was using Python 3.10.4

**Comment by andreped** [comment]
BTW: Did you mean that you downgraded Python or numpy? Quite a big difference. If Python 3.10.x don't work with our setup, we should remove it as a supported python version.

I assume that the numpy version you were using was numpy 1.23.2?

**Comment by GoldExplosion** [comment]
I meant numpy

**Comment by andreped** [comment]
> I meant numpy

Downgrade to which version from which version?

**Comment by andreped** [comment]
> Yes, I am using numpy 1.23.2

OK, I added info about this in the troubleshoot now: https://github.com/andreped/super-ml-pets/commit/4756f3e7b9d1d85423630d71989f45447d97c7a9

Alternatively we could set `numpy<=1.23.2` in the requirements.txt.

**Comment by andreped** [comment]
Also, was it during usage it failed, or during install of other stuff? Assuming it is the first, I have added a potential fix for it now:
1384090267ec5c32326d50ba2f50889a597903ed
