### ISSUE TITLE
Dynamic support for different monitors

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#17]
As different monitors may have different resolutions, this will affect the machine vision system which captures stuff on screen.

Currently, there exists hard-coded params for locations of objects on the screen, which will change if for instance a 4k monitor is used.

We should capture the resolution the game is one and scale the "hard-coded values" to make this more dynamic.

**Comment by andreped** [comment]
We should dynamically fetch the current screen resolution, and use this to scale the values seen [here](https://github.com/andreped/super-ml-pets/blob/main/src/image_detection.py#L26), [here](https://github.com/andreped/super-ml-pets/blob/main/src/image_detection.py#L113), and [here](https://github.com/andreped/super-ml-pets/blob/main/src/image_detection.py#L126).

**Comment by andreped** [comment]
Fixed in 6808de97b5df12c7c7058e062efa6fdfe3608959.

**Comment by andreped** [comment]
There was a minor bug left, which I have now fixed in b608c4e4e7c020f6f64a2b45d01d2dc23ddd588a.

It should now work as intended.

**Comment by MasonLyons** [comment]
Just tested this on a 1440p (2560×1440) screen and got the following when saving the output of https://github.com/andreped/super-ml-pets/blob/main/smp/image_detection.py#L50
![test](https://github.com/andreped/super-ml-pets/assets/11927887/ccbf2f6b-8744-4482-b274-1d23ee391ea7)

**Comment by andreped** [comment]
> Just tested this on a 1440p (2560×1440) screen and got the following when saving the output of [...]

Sadly others have observed the same, so this is definitely as problem. See https://github.com/andreped/super-ml-pets/issues/70#issuecomment-1762217580. As a result, I reopened this issue. Thanks for reporting It!

Not sure what is wrong, but I may take a look later today, unless you want to take a crack at it, @MasonLyons? Yo

**Comment by MasonLyons** [comment]
> > Just tested this on a 1440p (2560×1440) screen and got the following when saving the output of [...]
> 
> Sadly others have observed the same, so this is definitely as problem. See https://github.com/andreped/super-ml-pets/issues/70#issuecomment-1762217580. As a result, I reopened this issue. Thanks for reporting It!
> 
> Not sure what is wrong, but I may take a look later today, unless you want to take a crack at it, @MasonLyons? Yo

Sure, I can take a go at it. I'd need someone who has a 1080p screen to send me some examples of what their screen looks like. I'm not sure exactly how the game scales.

Doing some messing around last night, I removed 145 pixels from most of the x values and it started picking up the pets in the store other than the ones seemingly not added such as Mouse. 

The problem is it then made it not be able to see any of the food but I'm not sure how the images it uses for comparison are meant to look.

**Comment by andreped** [comment]
Any try is better than no try. I am sadly very busy with work and do not really have time for the project as much. I don't really play it anymore either, so I am not personally that motivated.

You can change the display on your laptop to 1080p to test. And then you can change the resolution to anything else, if you wish to debug and/or test if your proposed edit works.

Don't think about pets/items in this PR. Just focus on seeing if the extracted bounding boxes are from the right place. See this comment https://github.com/andreped/super-ml-pets/issues/70#issuecomment-1762217580 for an example on how to do it.

**Comment by MasonLyons** [comment]
> You can change the display on your laptop to 1080p to test. And then you can change the resolution to anything else, if you wish to debug and/or test if your proposed edit works.

I tried this, but as the game is still in full screen mode, it will automatically detect the screen is 1440p and run at that resolution.

> Don't think about pets/items in this PR. Just focus on seeing if the extracted bounding boxes are from the right place. See this comment [#70 (comment)](https://github.com/andreped/super-ml-pets/issues/70#issuecomment-1762217580) for an example on how to do it.
> 
> But note that changing the pets/items style is more critical. I would do that first. I can assign the task to you.

I agree that fixing the detection should be the priority. Unfortunately without the game running at 1080p or some screenshots and tests I can't solve that. I'll be trying to force it to 1080p tonight. The best way is to get screenshots from in game at different resolutions and build a test suite around it.

**Comment by andreped** [comment]
> I tried this, but as the game is still in full screen mode, it will automatically detect the screen is 1440p and run at that resolution.

I'm talking about changing the display resolution for the operating system, not just the game. Have you tried that? On windows you can visit the Display settings to see how to do that. That is a nice way to test different resolutions as well for debugging purposes, which you likely would need to do.

**Comment by andreped** [comment]
Fixed in https://github.com/andreped/super-ml-pets/commit/11853610f78153849c3423f5d8f71803619e6241.
