### ISSUE TITLE
The Sloth anomaly

### ISSUE THREAD

**Issue by GoldExplosion** [andreped/super-ml-pets#34]
If we take a look at the Pets under standard expansion, there is no sloth. But recently while playing in the standard pack the Pet Sloth appeared (It didn't occur to me to take a screenshot (ㅠ﹏ㅠ) ). 
This anomaly may cause the Computer Vision System to crash. Proper exceptions needed to prevent this.

**Comment by andreped** [comment]
Right now I have only considered the standard pack. 

However, AFAIK, the sloth is part of the standard pack, but is extremely rare, no?

As you can see here, the sloth is indeed part of the standard pack:
https://superautopets.fandom.com/wiki/Pets

I have actually seen the sloth once in the deployment stuff :P But yeah, we don't have a good way of handling this quite useless animal. The AI should hopefully learn to neglect it :P
