### ISSUE TITLE
Pip install fails in GitHub codespaces

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#45]
Just attempted to setup the project using GitHub codespaces, and during `pip install -r requirements.txt`, an error occurred:

```
Collecting sapai@ git+https://github.com/andreped/sapai.git@update-stats
  Cloning https://github.com/andreped/sapai.git (to revision update-stats) to /tmp/pip-install-eln35jls/sapai_2c0fd4b241034f06956f0a9abf03bed9
  Running command git clone --filter=blob:none --quiet https://github.com/andreped/sapai.git /tmp/pip-install-eln35jls/sapai_2c0fd4b241034f06956f0a9abf03bed9
  Running command git checkout -b update-stats --track origin/update-stats
  Switched to a new branch 'update-stats'
  branch 'update-stats' set up to track 'origin/update-stats'.
  Resolved https://github.com/andreped/sapai.git to commit bdc16215157a294194085be954d38c9a100a9b53
  Preparing metadata (setup.py) ... done
Collecting gym~=0.21.0
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 290.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by andreped** [comment]
It might be that the problem arises due to the space in one of the requirements:
https://github.com/andreped/sapai-gym/blob/catch-errors/setup.py#LL8C11-L8C75

**Comment by andreped** [comment]
Nevermind. The problem comes from installing `gym`.

Fixed in https://github.com/openai/gym/issues/3202#issuecomment-1488673956

**Comment by priyamalart** [comment]
I have similar issue with py3.8, can you suggest on this?
setuptools==66 was also modified.

14:12:26        Copying gym.egg-info to build/bdist.linux-x86_64/wheel/gym-0.21.0-py3.8.egg-info
14:12:26        running install_scripts
14:12:26        Traceback (most recent call last):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/requirements.py", line 35, in __init__
14:12:26            parsed = parse_requirement(requirement_string)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 64, in parse_requirement
14:12:26            return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 82, in _parse_requirement
14:12:26            url, specifier, marker = _parse_requirement_details(tokenizer)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 126, in _parse_requirement_details
14:12:26            marker = _parse_requirement_marker(
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 147, in _parse_requirement_marker
14:12:26            tokenizer.raise_syntax_error(
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_tokenizer.py", line 163, in raise_syntax_error
14:12:26            raise ParserSyntaxError(
14:12:26        wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
14:12:26            opencv-python>=3.
14:12:26                         ~~~^
14:12:26        
14:12:26        The above exception was the direct cause of the following exception:
14:12:26        
14:12:26        Traceback (most recent call last):
14:12:26          File "<string>", line 2, in <module>
14:12:26          File "<pip-setuptools-caller>", line 34, in <module>
14:12:26          File "/tmp/pip-wheel-34ur4kuy/gym_f74ca167b0dc4f1da53d4decc6d2d4f6/setup.py", line 39, in <module>
14:12:26            setup(
14:12:26          File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
14:12:26            return distutils.core.setup(**attrs)
14:12:26          File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
14:12:26            dist.run_commands()
14:12:26          File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
14:12:26            self.run_command(cmd)
14:12:26          File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
14:12:26            cmd_obj.run()
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 395, in run
14:12:26            self.egg2dist(self.egginfo_dir, distinfo_dir)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 534, in egg2dist
14:12:26            pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 160, in pkginfo_to_metadata
14:12:26            for key, value in generate_requirements({extra: reqs}):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 138, in generate_requirements
14:12:26            for new_req in convert_requirements(depends):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 103, in convert_requirements
14:12:26            parsed_requirement = Requirement(req)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/requirements.py", line 37, in __init__
14:12:26            raise InvalidRequirement(str(e)) from e
14:12:26        wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
14:12:26            opencv-python>=3.
14:12:26                         ~~~^
14:12:26        [end of output]
14:12:26    
14:12:26    note: This error originates from a subprocess, and is likely not a problem with pip.
14:12:26  [0m[91m  ERROR: Failed building wheel for gym
14:12:26  [0m  Running setup.py clean for gym

**Comment by andreped** [comment]
Hello, @priyamalart!

> I have similar issue with py3.8, can you suggest on this?

Hmm, interesting. This looks like a different issue. Could you make a new issue and we can move the discussion over there?

**Comment by priyamalart** [comment]
Reported https://github.com/andreped/super-ml-pets/issues/50 , Is this correct space to report the issue?

**Comment by andreped** [comment]
> Reported #50 , Is this correct space to report the issue?

Yup!
