### ISSUE TITLE
 ERROR: Failed building wheel for gym: wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)

### ISSUE THREAD

**Issue by priyamalart** [andreped/super-ml-pets#50]
While installing gym==0.21.0, this error is seen.
Its seems to be broken since 2-3 weeks.

14:12:26        Traceback (most recent call last):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/requirements.py", line 35, in __init__
14:12:26            parsed = parse_requirement(requirement_string)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 64, in parse_requirement
14:12:26            return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 82, in _parse_requirement
14:12:26            url, specifier, marker = _parse_requirement_details(tokenizer)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 126, in _parse_requirement_details
14:12:26            marker = _parse_requirement_marker(
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_parser.py", line 147, in _parse_requirement_marker
14:12:26            tokenizer.raise_syntax_error(
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/_tokenizer.py", line 163, in raise_syntax_error
14:12:26            raise ParserSyntaxError(
14:12:26        wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
14:12:26            opencv-python>=3.
14:12:26                         ~~~^
14:12:26        
14:12:26        The above exception was the direct cause of the following exception:
14:12:26        
14:12:26        Traceback (most recent call last):
14:12:26          File "<string>", line 2, in <module>
14:12:26          File "<pip-setuptools-caller>", line 34, in <module>
14:12:26          File "/tmp/pip-wheel-34ur4kuy/gym_f74ca167b0dc4f1da53d4decc6d2d4f6/setup.py", line 39, in <module>
14:12:26            setup(
14:12:26          File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
14:12:26            return distutils.core.setup(**attrs)
14:12:26          File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
14:12:26            dist.run_commands()
14:12:26          File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
14:12:26            self.run_command(cmd)
14:12:26          File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
14:12:26            cmd_obj.run()
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 395, in run
14:12:26            self.egg2dist(self.egginfo_dir, distinfo_dir)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 534, in egg2dist
14:12:26            pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 160, in pkginfo_to_metadata
14:12:26            for key, value in generate_requirements({extra: reqs}):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 138, in generate_requirements
14:12:26            for new_req in convert_requirements(depends):
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/metadata.py", line 103, in convert_requirements
14:12:26            parsed_requirement = Requirement(req)
14:12:26          File "/usr/local/lib/python3.8/site-packages/wheel/vendored/packaging/requirements.py", line 37, in __init__
14:12:26            raise InvalidRequirement(str(e)) from e
14:12:26        wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
14:12:26            opencv-python>=3.
14:12:26                         ~~~^
14:12:26        [end of output]
14:12:26    
14:12:26    note: This error originates from a subprocess, and is likely not a problem with pip.
14:12:26  [0m[91m  ERROR: Failed building wheel for gym
14:12:26  [0m  Running setup.py clean for gym
[building_wheel_gym_error.log](https://github.com/andreped/super-ml-pets/files/11140682/building_wheel_gym_error.log)

**Comment by andreped** [comment]
Yes, this looks identical to the issue mentioned [here](https://github.com/openai/gym/issues/3202).

I could try to see if I could fix `gym` myself on my own fork.

**Comment by andreped** [comment]
Went down a small rabbit hole and found something surprising. There is a breaking issue with `gym>=0.22` (see [here](https://github.com/DLR-RM/stable-baselines3/blob/5a70af8abddfc96eac3911e69b20f19f5220947c/setup.py#L102)), which sb3 depends on. Hence `sb3` has a strict dependency to only support `gym==0.21`, which seems to have all kinds of fun issues.

Hence, upgrading `gym` is not an option.

However, setting `setuptools==66` should resolve the issue. I observed something similar on colab and I managed to fix it by installing `pip install setuptools==66` before running `pip install -r requirements.txt` (see [here](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip) for more information).

It works on colab now but I will see if it passes the unit tests. Could you try to install the correct version of `setuptools` before trying to install the remainder of the deps?

**Comment by andreped** [comment]
I made a [gist](https://colab.research.google.com/gist/andreped/cc0789bd711874f792c0991978b2f981/super-ml-pets-test.ipynb) here for you to try. At least it works there.

**Comment by andreped** [comment]
All CI jobs were successful (see [here](https://github.com/andreped/super-ml-pets/actions/runs/4599895486/jobs/8125848634)). It also works fine on google colab (see [here](https://colab.research.google.com/gist/andreped/cc0789bd711874f792c0991978b2f981/super-ml-pets-test.ipynb)).

Are you sure you ran `pip install setuptools==66` before installing any dependencies? Did you create a virtual environment?

Lastly, it might be that upgrading pip resolves the issue. In the colab, I'm using a very new version of pip. Try upgrading to latest:
```
pip install --upgrade pip
```

**Comment by priyamalart** [comment]
@andreped : setuptools were added in requirement.txt. It was installed alng with other python modules.
And, Iam using python:3.8 container image, And we havent created any virtual env.

Let me try to upgrade the pip.

**Comment by priyamalart** [comment]
**Working Solution:**
pip3 install --no-cache-dir --no-deps -r requirements.txt --timeout 60 --> Here, setuptools==66 was used. pip upgrade was not done.

**Non-Working Solution:**
pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt --timeout 60 

**Why we use wheels?**
Machine learning based container images are very huge.
So, we use the python image to install wheels and then only wheels are copied to final image. This reduces the final image size.

Ex:

FROM python:3.8 as builder
RUN mkdir -p /ws/
WORKDIR "/ws/"
COPY src/requirements.txt requirements.txt
RUN pip3 install --upgrade pip \
    && pip3 install --no-cache-dir --no-deps setuptools==66 --timeout 60 \
    && **pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt --timeout 60 \**
    && rm -rf /ws
WORKDIR "/"

FROM python:3.8-slim as runner
RUN mkdir -p /ws/
WORKDIR "/ws/"
**COPY --from=builder /wheels /wheels**
#RUN pip install --upgrade pip \
RUN **pip install --no-cache-dir --no-deps /wheels/* \**
    && rm -rf /wheels \
    && rm -rf /ws

**Comment by andreped** [comment]
Ok, it seems like `--no-deps` is the key here.

We use docker as well when we run the CI tests. It is still strange to me why it didn't work for you while it seems to work most other places.

As you use docker, it might be that you are missing some key dependency that resolves this.

**Comment by priyamalart** [comment]
But, in our case, Error is seen in this step:
pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt --timeout 60

**Comment by andreped** [comment]
Aaah, I see. But is it only through the Dockerfile-install that it fails or does it work outside docker?

**Comment by andreped** [comment]
Just tried running this line on my windows laptop:
```
pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt --timeout 60
```

Works fine. However, in my case most of the wheels were already.

Perhaps it is easier if I build a `sapai-gym` myself and use that one instead. Then you do not need to compiled your own wheels during installation. I'm testing this now [here](https://github.com/andreped/sapai-gym/actions).

**Comment by andreped** [comment]
I have now built precompiled wheel for `sapai-gym` (see [here](https://github.com/andreped/sapai-gym/releases/tag/v0.1.1)).

All CIs seem to work (see [here](https://github.com/andreped/super-ml-pets/actions/runs/4605905115).

Hence, if you try cloning/pull latest commit, I believe it might work.

**Comment by priyamalart** [comment]
Within docker, we use 2 OS.
1. Ubuntu --> Installation is okay
2. Python3.8 images based on debian. --> Issue is seen here. 
I might have to understand, the package difference between these base OS and python modules.

**Comment by andreped** [comment]
Just tried to setup `super-ml-pets` on a personal windows laptop and I ran into the same issue still. Preinstalling `setuptools==66` resolves the issue.

Thus, precompiling wheel for `sapai-gym` is not sufficient. We will need to precompile wheel for `gym`. I could make an attempt.

**Comment by andreped** [comment]
I have now precompiled wheels for `sapai-gym` and `gym`, so maybe you will be more lucky this time around. Try to pull latest and try again.

**Comment by andreped** [comment]
> pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt --timeout 60

I also tried running this command locally and it works fine. From the verbose it is also clear that it downloads the precompiled wheels (and does not build `gym`).

**Comment by priyamalart** [comment]
I always tried to install setuptool==66 and gym==0.21.0. With this error persists.
With latest gym version, issue doesnt occur.

**Comment by andreped** [comment]
What do you mean by latest gym version? Newer than 0.21? Those are not compatible with simple-basline3 (sb3).

I have precompiled the 0.21 wheel now and released it in my own fork. I believe that should work, as building during install is no longer required. Was it that you tried?

**Comment by priyamalart** [comment]
Yes, gym==0.26.2 installation works. 
Off course, We also can't migrate to latest gym - 0.26.2.

>>> What should be tried here? How to do this or any links to follow?
I believe that should work, as building during install is no longer required. Was it that you tried?

**Comment by andreped** [comment]
> I have precompiled the 0.21 wheel now and released it in my own fork. I believe that should work, as building during install is no longer required. Was it that you tried?

^again. I should have fixed this in my own release of `gym`, which my own `sapai-gym` depends on (see [here](https://github.com/andreped/sapai-gym/blob/catch-errors/requirements.txt#L2)). 

In order to properly get that fix, you will likely need to do `--no-cache-dir` to ensure that you get the updated `wheel` of `sapai-gym`, as I only updated the wheel itself and did not make a new release.

So please, try setting up the docker image again, if thats what you are trying to do.

If all this does not work, I will need a reproducible bash script demonstrating what you are trying to do, including the `Dockerfile`.

**Comment by andreped** [comment]
Great! What do you mean with "release your change"?

It is already part of `super-ml-pets`, as the the `gym` wheel above is part of the [sapai-gym](https://github.com/andreped/super-ml-pets/blob/main/requirements.txt#L2) dependency here (which has been recently updated).

Does everything work now for you?

**Comment by priyamalart** [comment]
I misunderstood, the correction will be published to https://pypi.org/project/gym/#history.
Now, all issues are sorted out. Thanks for your support.
