### ISSUE TITLE
Reduce project size

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#53]
Right now the entire repo is about 327 MB, which is way higher than the recommended maximum size of 100 MB.

This also means that it takes very long to clone.

**Comment by andreped** [comment]
Apparently the `.git` directory contains ~300 MB. It is likely due to storing history on a large number of image files, which should not be necessary.

**Comment by andreped** [comment]
The `.git/objects/pack/*.pack` is where the magic happens. Should be possible to avoid storing history of these image files. Likely using Large File Storage (LFS) solved this issue, but from experience, it is annoying to remove LFS when first added to a project.

**Comment by Potajito** [comment]
Yeah, I'm leaning towards that too. I had to revert to old style icons for it to see the animals, but I think it still has trouble with the interface. Gonna tinker a bit on my side too.

**Comment by andreped** [comment]
I have removed all icons from `src/*`, hence, it should be a lot smaller in future releases.

However, we might have to _rewrite history_ to fully resolve the issue, but I think it is OK for now. Can re-open or open a new issue, if relevant.
