### ISSUE TITLE
SAP's UI and animals have updated - machine vision system needs updating

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#55]
Switching to classical style partly resolves this issue as mentioned in https://github.com/andreped/super-ml-pets/issues/52#issuecomment-1500241721.

This uses the old style of the animals. However, the UI might still be slightly different.

**Comment by laughinggaschambers** [comment]
I'm having issues getting it to see anything, might be related but switching between classic and standard doesn't help a bit. This was a fresh install. Windows 10.
![image](https://user-images.githubusercontent.com/114764161/231082598-a7432644-4f50-4300-a38f-10839fe5c165.png)

**Comment by andreped** [comment]
Hello, @laughinggaschambers! :]

> I'm having issues getting it to see anything, might be related but switching between classic and standard doesn't help a bit. This was a fresh install. Windows 10.

This is a exactly the same as observed in issue https://github.com/andreped/super-ml-pets/issues/52.

Basically, all pets' icons needs updating, AFAIK. However, both you and @Potajito actually find pets on the windows version, whereas I had issues from the web app. Might be that this is easier to solve than I first anticipated, and that reverting to the old style actually resolves the icon issue. But that means that there is another cause for this issue.

**Comment by laughinggaschambers** [comment]
Did a little poking around the code, a dirty quick fix is to
set action = int(action) in deploy_agent.py at line 125
it runs then.

**Comment by andreped** [comment]
I saw you made a PR. Great! I made a comment which it would be great if you addressed before merging, see https://github.com/andreped/super-ml-pets/pull/56

**Comment by andreped** [comment]
Fixed in https://github.com/andreped/super-ml-pets/pull/56.

I also added the additional step of changing the UI style in the deployment instructions in be6857123bce5b52d926adb38e7f44b6da6823f1.

**Comment by andreped** [comment]
Just tested this now on my windows laptop at home, and it does indeed work. However, I came across another issue, related to event regarding health after a game.
