### ISSUE TITLE
New UI event causes bot the crash

### ISSUE THREAD

**Issue by andreped** [andreped/super-ml-pets#57]
This was observed after two games of playing, where the bot had lost the first game but won the second.

This happens right after the shop UI is shown after a game. Hence, the auto-clicker has stopped, and thus, the bot thinks it is looking at the shop.

A fix could be to click one second longer after the shop UI has shown, to automatically skip this prompt.

![20230411180738_1](https://user-images.githubusercontent.com/29090665/231224058-c149daed-6e1a-42a2-8584-9a47e73542f4.jpg)

**Comment by laughinggaschambers** [comment]
Yeah, I forgot to mention that this happened, sent a pr for the fix

**Comment by andreped** [comment]
Great! There is a merge conflict it would be great if you could resolve in the PR https://github.com/andreped/super-ml-pets/pull/59#pullrequestreview-1380001461

**Comment by andreped** [comment]
Fixed in d4e889b024b5bae848188ff49fc78b4102c2feae.
