### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by adjmathix** [andreped/super-ml-pets#66]
**Describe the bug**
When tyring to train the model, I have either a module or AttributeError.

**To Reproduce**
Following the steps in the README.txt for setup.

When I'm ready to train I run:
python main.py --task train
-> it gives me an error for not having the module shimmy 0.2.1 installed.
after pip install shimmy>=0.2.1, I run again the train command line and now I have:
AttributeError: 'SuperAutoPetsEnv' object has no attribute 'render_mode'
**Desktop (please complete the following information):**
 - OS: Windows 10

I know this project is starting to date a bit but hopefully someone is going to read this issue. I would love to have it working.

**Comment by andreped** [comment]
Hello, @adjmathix!

I managed to reproduce the bug on CoLab (see [gist](https://colab.research.google.com/gist/andreped/5345bb3f78ab1641efde05e2f099d93b/super-ml-pets-test.ipynb)).

Basically, it seems like there is something that has changed in stable baseline3 or any of its dependencies, resulting in the bug you are observing.

I will make a PR, if I find a solution to this problem.

**Comment by andreped** [comment]
I found a simple fix. The latest `sb3-contrib` is not compatible with the environment. By simply forcing to use a specific version, it fixes the problem (see updated [gist](https://colab.research.google.com/gist/andreped/c3ec5b6ee5c68c29fddd26a92396b1c7/super-ml-pets-test.ipynb)).

**Comment by andreped** [comment]
Fixed in 9e12fe1fbd24453301e7d26f1304285b663d60af.

All unit tests passed, so I assume this works. Pull latest and try again.

**Comment by adjmathix** [comment]
That works on my side too! Thanks for the quick fix.
