### ISSUE TITLE
No animal/food detected

### ISSUE THREAD

**Issue by adjmathix** [andreped/super-ml-pets#69]
**Describe the bug**
While running a model in the game, I noticed that no animals or foods were detected. The model repeatedly clicks Roll.
I have adjusted the different display/UI settings.

**To Reproduce**
Run a model in game.

**Screenshots**
INFO deploy_agent.py 114 CV SYSTEM [self.run]: The detected Pets and Food in the Shop is : []

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by andreped** [comment]
Are you just trying to run the deployment using the released pretrained model?

What did you adjust in terms of display and all that and why did you have to do that? I assume it is because your screen resolution differ?

**Comment by adjmathix** [comment]
I was using a model I trained, I was taking the .zip file under the model folder (excluding the extension when running). It does the samething with the released model.
During the first round, it's only clicking Roll and on the second round, it's clicking on the top right on the screen.

For the display, I meant that I was following the instructions under Testing;

Ensure that the game is in full screen mode, disable all unneccessary prompts, enable auto name picker, and set speed to 200% (you might also have to enable auto battle which can only be done in the first battle - if this is the first time you are playing this game).
Change the UI style to classic for all options in customize including "Food art", "Background art", "Menu background", "Buff style", and "Held food".
Change UI style for pets to classic by going to the pets settings.

**Comment by andreped** [comment]
Could be that something has changed with the UI, making parts of the computer vision system failing to capture the right events and the store.

I can have a look tomorrow. Travelling today.

**Comment by adjmathix** [comment]
That would be my guess. No problem, safe travel.

**Comment by andreped** [comment]
This issue seems related to an existing issue: https://github.com/andreped/super-ml-pets/issues/61

We should move the discussion there instead.

As this is a duplicate and I am closing this issue.
